### ISSUE TITLE
[FEAT] - Updates and Refactoring for Node 20

### ISSUE THREAD

**Issue by dgrebb** [dgrebb/BackstopJS#34]
# Requirements

The project should be installed and run with Node 20. As gaps are identified, create issues for larger lifts, or add tasks below to upgrade specific dependencies one at a time.

# Tasks

- [x] install BackstopJS from `master` using Node 20
- [x] update dependencies with `ncu`
- [ ] update `Dockerfile` to Node 20 (#40)
- [ ] validate `santiy-test-docker`
- [x] validate `sanity-test`
- [x] validate [ember-backstop](https://github.com/garris/ember-backstop)
- [x] validate `remote`
- [x] validate `test`
- [x] validate `reference`
- [x] validate `approve`
- [x] create dependency compatibility issues

## Compatibility Tests

- [x] test Node 14
- [x] test Node 16
- [x] test Node 18

**Comment by garris** [comment]
Only thing I'd add is to check that basic tests pass in the [ember-backstop](https://github.com/garris/ember-backstop) project as well.   There is some risk that changes to remote could cause a regression there.

**Comment by dgrebb** [comment]
@garris  FYA — BackstopJS `master` works on Node 20 out of the box :) 

I'll keep this open as the main issue for all dependency updates pending what we decide in #39.

**Comment by dgrebb** [comment]
@garris great progress! Please see below failing functional (manual), unit, and integration tests.

# Functional Tests Performed

- [x] `npm run init`
- [x] `npm run reference`
- [x] `npm run test`
- [x] `npm run remote`
- [x] `npm run stop`
- [x] `npm run approve`
- [x] `npm run openReport`
- [x] `npm run report`
- [ ] `npm run unit-test` - fails — details below in "Unit Tests Performed"
- [ ] `npm run build-compare` - fails — to be addressed with #38
- [ ] `npm run dev-compare` - fails — to be addressed with #38
- [ ] `npm run genConfig` - fails — should this be `makeConfig`, and exposed in `runner.js`?
- [ ] `npm run echo` - fails (should this be `makeConfig`, and exposed in `runner.js`?)
- [ ] `npm run integration-test` - fails — `genConfig` is not exposed publicly
- [ ] `npm run smoke-test` - succeeds? mismatch errors found; report opens in browser
- [ ] `npm run smoke-test-docker` - succeeds? mismatch errors found; report opens in 
- [ ] `npm run smoke-test-playwright-docker` - succeeds? mismatch errors found; report opens in browser
- [ ] `npm run sanity-test-palywright` - succeeds? mismatch errors found; report opens in browser
- [x] `npm run kill-zombies`
- [x] `npm run copy-report-bundle`
- [ ] `build-and-copy-report-bundle` - fails — to be addressed with #38
- [ ] publish-npm
- [x] `npm run build-docker`
- [x] `npm run docker-load`
- [ ] publish-docker
- [ ] build-and-publish
- [x] `npm run init-docker-builder`


## Unit Tests Performed

All passing, except `compare_spec.js` — where are `img1.png` and `img2.png`?

```bash
  compare
    - should resolve if compare-hashes succeed
    - should resolve if compare-hashes fail, but compare-resemble succeeds
    - should reject if compare-hashes and compare-resemble fail
```

## Docker Validations Performed

_Note: a `npm run docker-load` script was added to load local `buildx` multi-platform image without publishing_

- [x]`cd test/configs/ && node ../../cli/index.js test --docker`
- [x] `npm run sanity-test-docker`
-  [ ]`npm run smoke-test-docker` - exits without indication of passing smoke tests; report opens in browser. expected?
-  [x] `npm run sanity-test-playwright-docker`

**Comment by garris** [comment]
Great!  Did you want to book a time to review the different fail cases?

**Comment by dgrebb** [comment]
@garris sounds good. I'm digging into Ember next. After that, we can review everything in one go. I'll reach out to coordinate a time when everything is ready. Thank you!

**Comment by dgrebb** [comment]
@garris Ember.js checks out! This is all running with Node 20. Here are:

- [`ember-playground`](https://github.com/dgrebb/ember-playground), [which uses](https://github.com/dgrebb/ember-playground/blob/develop/package.json#L39) the below `ember-backstop` fork
- [ember-backstop](https://github.com/dgrebb/ember-backstop): forked with a [branch running `backstopjs@6.3.0`](https://github.com/dgrebb/ember-backstop/blob/feature/backstop-6.3.0/package.json#L30)

## EmberJS Test Dashboard

In Ember's test runner dashboard, before and after accepting the first backstop run, the report image displays, then disappears. Is this expected?

![2023-11-04 12 38 18](https://github.com/dgrebb/BackstopJS/assets/445891/eed1deb7-71c9-460e-a02a-7894385fdac9)

## Backstop Remote running via `ember backstop-remote`

![image](https://github.com/dgrebb/BackstopJS/assets/445891/be27a0bf-6c26-4e4e-8ccd-adc7f0ddb762)

**Comment by garris** [comment]
Wow Amazing work!!   This is ridiculous -- there will be a lot of backstop users who are super thankful for this!

**Comment by garris** [comment]
And yeah -- I'm not sure about the QuickStart tests -- I am not that concerned about it as long as the tests give consistent results.

**Comment by dgrebb** [comment]
I'll get a list of items for review and get back to you with some times this week. Thank you!

**Comment by dgrebb** [comment]
# Node Testing

@garris one more update, regarding Node version testing:

## Node 18

Works!

## Node 16

Works!

## Node 14

It appears later versions of `puppeteer` do not play nice with `node@14`. Node 14 also requires a downgrade to `python <=3.10.x`, so maybe it's time to drop support?

```shell
added 1022 packages from 768 contributors and audited 1024 packages in 23.222s

209 packages are looking for funding
  run `npm fund` for details

found 4 vulnerabilities (1 low, 2 high, 1 critical)
  run `npm audit fix` to fix them, or `npm audit` for details
❯ npm run sanity-test

> backstopjs@6.3.0 sanity-test ~/Projects/BackstopJS
> cd test/configs/ && node ../../cli/index.js test

~/Projects/BackstopJS/node_modules/puppeteer-core/lib/cjs/puppeteer/util/disposable.js:19
Symbol.dispose ??= Symbol('dispose');
               ^^^

SyntaxError: Unexpected token '??='
    at wrapSafe (internal/modules/cjs/loader.js:1029:16)
    at Module._compile (internal/modules/cjs/loader.js:1078:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
    at Module.load (internal/modules/cjs/loader.js:979:32)
    at Function.Module._load (internal/modules/cjs/loader.js:819:12)
    at Module.require (internal/modules/cjs/loader.js:1003:19)
    at require (internal/modules/cjs/helpers.js:107:18)
    at Object.<anonymous> (~/Projects/BackstopJS/node_modules/puppeteer-core/lib/cjs/puppeteer/common/EventEmitter.js:23:25)
    at Module._compile (internal/modules/cjs/loader.js:1114:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! backstopjs@6.3.0 sanity-test: `cd test/configs/ && node ../../cli/index.js test`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the backstopjs@6.3.0 sanity-test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     ~/.npm/_logs/2023-11-07T02_17_49_762Z-debug.log
❯ node -v
v14.21.3
```

**Comment by garris** [comment]
Agree,  let's drop support for 14.  Let's please add at the top of the docs requirements section.

**Comment by dgrebb** [comment]
https://github.com/garris/BackstopJS/pull/1523
