### ISSUE TITLE
[FEAT] - Compare - Dependency Refresh

### ISSUE THREAD

**Issue by dgrebb** [dgrebb/BackstopJS#35]
# Requirements

Update `compare` ecosystem dependencies and build `src` to `output` with latest React, Babel, and Webpack.

# Tasks

- [x] after updating dependencies, refactor `webpack.config.js` as needed (static image assets etc.)
- [x] build compare successfully
- [x] test browser regressions
  - [x] Safari
  - [x] Chrome
  - [x] Firefox
  - [x] Edge
- [x] add issues for larger lifts

**Comment by dgrebb** [comment]
Closed by https://github.com/garris/BackstopJS/pull/1532
