### ISSUE TITLE
[FEAT] - Update backstop-twentytwenty Dependencies

### ISSUE THREAD

**Issue by dgrebb** [dgrebb/BackstopJS#36]
# Requirements

Update backstop-twentytwenty to latest Webpack, Babel, and React.

# Tasks

- [x] reconfigure webpack as needed
- [x] adjust React where needed
- [x] test in Node 20 via `sanity-test` in main project
- [x] test in Node 18 via `sanity-test` in main project
- [x] test in Node 16 via `sanity-test` in main project (nice to have)
- [x] add issues for larger lifts

**Comment by dgrebb** [comment]
Closed by https://github.com/garris/BackstopJS/pull/1532
